### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by nayramartins** [sputnk/fuzzer#8]
Create login screen following the _fuzzer_ visual identity.

**Must have:**

- [x] Visual specifications on Zeplin https://zpl.io/be1R3wP
- [x] Title component that will be reused along the project https://github.com/sputnk/fuzzer/issues/9
- [x] Button component with the label "LOGIN WITH SPOTIFY" https://github.com/sputnk/fuzzer/issues/11
- [x] Background image on bottom following the visual specification. https://github.com/sputnk/fuzzer/issues/25
- [ ] Login service https://github.com/sputnk/fuzzer/issues/16
